# Generated by Django 4.0.4 on 2022-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='person',
            new_name='user',
        ),
    ]
