# Generated by Django 4.0.4 on 2022-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
        ('users', '0003_rename_person_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.ManyToManyField(to='therapy.disease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptomes',
            field=models.ManyToManyField(to='therapy.symptom'),
        ),
    ]
