# Generated by Django 4.0.4 on 2022-05-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_patient_diseases_patient_symptomes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='symptomes',
            new_name='symptoms',
        ),
    ]
