# Generated by Django 4.0.4 on 2022-05-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_remove_symptom_diseases'),
        ('users', '0005_rename_symptomes_patient_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='therapy.disease'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='therapy.symptom'),
        ),
    ]
