# Generated by Django 4.0.4 on 2022-05-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0003_delete_ticket'),
        ('users', '0006_alter_patient_diseases_alter_patient_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cooperation.hospital'),
        ),
    ]
