# Generated by Django 4.0.4 on 2022-05-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0007_patient_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bill',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.PROTECT, to='payments.bill'),
            preserve_default=False,
        ),
    ]
