# Generated by Django 4.0.4 on 2022-05-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0008_patient_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bill',
            field=models.OneToOneField(default=15, on_delete=django.db.models.deletion.PROTECT, to='payments.bill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bill'),
        ),
    ]
