# Generated by Django 4.0.4 on 2022-05-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='diseases',
        ),
    ]
