# Generated by Django 4.0.4 on 2022-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=254)),
                ('amount', models.BigIntegerField(default=0)),
                ('change', models.IntegerField(default=0)),
            ],
        ),
    ]
