# Generated by Django 4.0.4 on 2022-05-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bill_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='last_change',
            field=models.DateTimeField(),
        ),
    ]
