# Generated by Django 4.0.4 on 2022-05-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='last_change',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
