# Generated by Django 4.0.4 on 2022-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_bill_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='change',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='info',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='last_change',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
