# Generated by Django 4.0.4 on 2022-05-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='start_date',
        ),
    ]
