# Generated by Django 4.0.4 on 2022-05-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0002_remove_ticket_end_date_remove_ticket_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
