# Generated by Django 4.0.4 on 2022-05-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('cooperation', '0003_delete_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bill'),
        ),
    ]
