# Generated by Django 4.0.4 on 2022-05-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('cooperation', '0004_hospital_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.bill'),
        ),
    ]
