# Generated by Django 4.0.4 on 2022-05-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment'),
        ('cooperation', '0005_alter_hospital_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='bill',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bill'),
        ),
    ]
